rm -rf "../synth/__projnav" 
rm -rf "../synth/xst" 
rm -rf "../synth/_ngo" 

rm -rf tmp 
rm -rf _xmsgs 
rm -rf vio_sync_out32_xdb 
rm -rf vio_async_in96_xdb 
rm -rf vio_async_in100_xdb 
rm -rf vio_async_in192_xdb 
rm -rf icon4_xdb 

rm -rf xst 
rm -rf xlnx_auto_0_xdb 

rm -rf coregen.cgp
rm -rf coregen.cgc
rm -rf coregen.log 
rm -rf vio_sync_out32.asy 
rm -rf vio_sync_out32.cdc 
rm -rf vio_sync_out32.gise 
rm -rf vio_sync_out32.ise 
rm -rf vio_sync_out32.ncf 
rm -rf vio_sync_out32.ngc 
rm -rf vio_sync_out32.xco 
rm -rf vio_sync_out32.xise 
rm -rf vio_sync_out32_flist.txt 
rm -rf vio_sync_out32_readme.txt 
rm -rf vio_sync_out32_xmdf.tcl 

rm -rf vio_async_in100.asy 
rm -rf vio_async_in100.cdc 
rm -rf vio_async_in100.gise 
rm -rf vio_async_in100.ise 
rm -rf vio_async_in100.ncf 
rm -rf vio_async_in100.ngc 
rm -rf vio_async_in100.xco 
rm -rf vio_async_in100.xise 
rm -rf vio_async_in100_flist.txt 
rm -rf vio_async_in100_readme.txt 
rm -rf vio_async_in100_xmdf.tcl 


rm -rf vio_async_in192.asy 
rm -rf vio_async_in192.cdc 
rm -rf vio_async_in192.gise 
rm -rf vio_async_in192.ise 
rm -rf vio_async_in192.ncf 
rm -rf vio_async_in192.ngc 
rm -rf vio_async_in192.xco 
rm -rf vio_async_in192.xise 
rm -rf vio_async_in192_flist.txt 
rm -rf vio_async_in192_readme.txt 
rm -rf vio_async_in192_xmdf.tcl 

rm -rf vio_async_in96.asy 
rm -rf vio_async_in96.cdc 
rm -rf vio_async_in96.gise 
rm -rf vio_async_in96.ise 
rm -rf vio_async_in96.ncf 
rm -rf vio_async_in96.ngc 
rm -rf vio_async_in96.xco 
rm -rf vio_async_in96.xise 
rm -rf vio_async_in96_flist.txt 
rm -rf vio_async_in96_readme.txt 
rm -rf vio_async_in96_xmdf.tcl 

rm -rf icon4.gise 
rm -rf icon4.ise 
rm -rf icon4.ncf 
rm -rf icon4.ngc 
rm -rf icon4.xco 
rm -rf icon4.xise 
rm -rf icon4_flist.txt 
rm -rf icon4_readme.txt 
rm -rf icon4_xmdf.tcl 

rm -rf ise_flow_results.txt 
rm -rf xlnx_auto_0.ise 
rm -rf mig_v3_4_vhdl.prj 
rm -rf mem_interface_top.syr 
rm -rf mig_v3_4.ngc 
rm -rf mig_v3_4.ngr 
rm -rf mig_v3_4_xst.xrpt 
rm -rf mig_v3_4.bld 
rm -rf mig_v3_4.ngd 
rm -rf mig_v3_4_ngdbuild.xrpt 
rm -rf mig_v3_4_map.map 
rm -rf mig_v3_4_map.mrp 
rm -rf mig_v3_4_map.ngm 
rm -rf mig_v3_4.pcf 
rm -rf mig_v3_4_map.ncd 
rm -rf mig_v3_4_map.xrpt 
rm -rf mig_v3_4_summary.xml 
rm -rf mig_v3_4_usage.xml 
rm -rf mig_v3_4.ncd 
rm -rf mig_v3_4.par 
rm -rf mig_v3_4.xpi 
rm -rf smartpreview.twr 
rm -rf mig_v3_4.ptwx 
rm -rf mig_v3_4.pad 
rm -rf mig_v3_4.unroutes 
rm -rf mig_v3_4_pad.csv 
rm -rf mig_v3_4_pad.txt 
rm -rf mig_v3_4_par.xrpt 
rm -rf mig_v3_4.twx 
rm -rf mig_v3_4.bgn 
rm -rf mig_v3_4.twr 
rm -rf mig_v3_4.drc 
rm -rf mig_v3_4_bitgen.xwbt
rm -rf mig_v3_4.bit 

# Files and folders generated by create ise
rm -rf test_xdb
rm -rf _xmsgs
rm -rf test.gise
rm -rf test.xise
rm -rf test.ise

# Files and folders generated by ISE through GUI mode
rm -rf _ngo
rm -rf xst
rm -rf mig_v3_4.lso 
rm -rf mig_v3_4.prj 
rm -rf mig_v3_4.xst 
rm -rf mig_v3_4.stx 
rm -rf mig_v3_4.syr 
rm -rf mig_v3_4_prev_built.ngd 
rm -rf test.ntrc_log 
rm -rf mig_v3_4_guide.ncd 
rm -rf mig_v3_4.ut 
rm -rf mig_v3_4.cmd_log 
rm -rf par_usage_statistics.html
rm -rf usage_statistics_webtalk.html
rm -rf webtalk.log
rm -rf device_usage_statistics.html 
rm -rf mig_v3_4_summary.html 
