Top=v5_mig34
OnlyTargets=virtex5
SourceFiles=\
 mig_v3_4/user_design/rtl/ddr2_ctrl.v\
 mig_v3_4/user_design/rtl/ddr2_mem_if_top.v\
 mig_v3_4/user_design/rtl/ddr2_phy_calib.v\
 mig_v3_4/user_design/rtl/ddr2_phy_ctl_io.v\
 mig_v3_4/user_design/rtl/ddr2_phy_dm_iob.v\
 mig_v3_4/user_design/rtl/ddr2_phy_dq_iob.v\
 mig_v3_4/user_design/rtl/ddr2_phy_dqs_iob.v\
 mig_v3_4/user_design/rtl/ddr2_phy_init.v\
 mig_v3_4/user_design/rtl/ddr2_phy_io.v\
 mig_v3_4/user_design/rtl/ddr2_phy_top.v\
 mig_v3_4/user_design/rtl/ddr2_phy_write.v\
 mig_v3_4/user_design/rtl/ddr2_top.v\
 mig_v3_4/user_design/rtl/ddr2_usr_addr_fifo.v\
 mig_v3_4/user_design/rtl/ddr2_usr_rd.v\
 mig_v3_4/user_design/rtl/ddr2_usr_top.v\
 mig_v3_4/user_design/rtl/ddr2_usr_wr.v\
 ddr2_idelay_ctrl_eco20100514.v\
 ddr2_infrastructure_eco20100512.v\
 v5_mig34.v

