#!/bin/csh
if ($#argv != 2) then
    echo $0{}: Usage is: lbsN210 bit_file USB_portname
    exit 1
endif
set bitfile = $argv[1]
set usbport = $argv[2]

set temp = /tmp/ocpibitstream$$
set tscript =  $temp.1
set tbar = $temp.2
set tlog = $temp.3

echo Loading bit file $bitfile via usb port $usbport.

cat > $tscript <<EOF
setMode -bs
setCable -port $usbport
Identify
IdentifyMPM
assignFile -p 1 -file $bitfile
Program -p 1
exit
EOF

echo Loading bitstream...
impact -batch $tscript >& $tlog

if ($status != 0) then
  echo Error: impact bitstream loader failed. See $tlog
  echo Error log says: `grep -i error $tlog`
else
  grep -q 'Programmed successfully' $tlog
  if ($status != 0) then
    echo Error: bit stream loading did not succeed.
  else
    echo Bitstream loaded successfully
  endif
endif


