#!/bin/csh
if ($#argv != 1) then
    echo $0{}: Usage is: loadBothBitStreams bit_file
    exit 1
endif
set bitfile = $argv[1]
sudo ./ocfrp_check
sudo ./loadBitStream $bitfile 0000:03:00.0 usb21
sudo ./loadBitStream $bitfile 0000:04:00.0 usb22
sudo ./ocfrp_check
